### ISSUE TITLE
Remove prefer option from _getStringStream

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [Syncurity/msg-extractor#39]
The existence of more than one type of encoding in the same msg file is NOT to msg standard. As such, this option is completely unnecessary, and actually would violate the standard.

**Comment by punkrokk** [comment]
So - should we just throw a warning and fail safe? Have you seen in the wild?

Cheers,

JP

**Comment by TheElementalOfDestruction** [comment]
No, we are using the msg files properties to determine which we look for. We don't check at all of other versions exist. That's the job of the validation submodule
